### PR TITLE
Update to hybrid element

### PR DESCRIPTION
**Pull request by Mihaiii**
Update to hybrid element
For https://github.com/Starcounter/RebelsLounge/issues/140 .

### CODE REVIEW

**Review by PatrykSzwer — COMMENTED** [review]
I'm not sure if I'm right person to review it. For me It looks good, but I would like to politely ask @tomalec to review it as well.

**Comment by warpech** [comment]
If you tested the Polymer 1.x version in KitchenSink, where the current version of `starcounter-upload` is used.

As well as with Polymer 2 in the `index.html` demo using polyserve, then I think this is enough of a test.

**Review by PatrykSzwer — CHANGES_REQUESTED** [review]
I've tested this with polyserve, and heres what I've got:
From master branch:
image

from this branch:
image

Files do not show in a table, but above.

**Comment by Mihaiii** [comment]
Thank you! Fixed.

**Review by PatrykSzwer — APPROVED** [review]
Now It looks ok. BTW during running this in polyserve, there is a tip that says: `Click Ctrl + V to paste image from clipboard` which is not working (or I don't know how to use it) but It's also not working in master branch so It's not part of this PR.

**Pull request merged**
